### ISSUE TITLE
create new voting type: yes/no

### ISSUE THREAD

**Issue by antoniomaqueda** [part-pantoja/decide#10]

**Comment by jaime-carbo** [comment]
Asígnale a la issue la branch en la que estas haciendo estos cambios
Tenemos que describir cada una de las issues que creemos. Tiene que quedar claro cual es el producto final que se busca tras terminar la feature.

**Comment by antoniomaqueda** [comment]
Crear un nuevo tipo de votación donde se tengan los valores predefinidos Si/No.

El administrador podrá crear una pregunta de tipo yes-no y se mostrará en pantalla al usuario siempre con el titulo "si" "no.
