### ISSUE TITLE
Bug Detectado: "Fallos tests en Codacy"

### ISSUE THREAD

**Issue by PabloPinMat** [part-pantoja/decide#145]
Al ejecutar los test en codacy hay dos fallos del modulo voting. El servidor debe estar desplegado para que los test funcionen.

El error se puede ver en el Actions de GitHub

![Captura](https://github.com/part-pantoja/decide/assets/100594476/2c60c413-e20d-4960-919d-d92137c76409)

**Comment by andressomoza** [comment]
Ya funciona
