### ISSUE TITLE
create census request

### ISSUE THREAD

**Issue by eloyjm** [part-pantoja/decide#19]
Creación de un sistema que permite a un usuario logueado realizar una solicitud de unión a un censo. Dicha solicitud contiene un estado, votacion y user. El admin se encargará de aceptar la solicitud mediante acciones en /admin. Al aceptar la solicitud, se añade el usuario al censo. Existirán varias pantallas en caso de realizar la solicitud mas de una vez, o a una votación cerrada.
Validación: Al crear la solicitud, aparece correctamente en el panel de administración, y funciona la lógica de aceptar o rechazar.

**Comment by jaime-carbo** [comment]
Tenemos que describir cada una de las issues que creemos. Tiene que quedar claro cual es el producto final que se busca tras terminar la feature.
